In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8086, 2639, 5411, 4339],
 [8086, 2639, 5411, 1099],
 [8086, 1844, 5411, 7151],
 [7820, 2331, 8302, 8722, 3846],
 [7820, 2331, 8302, 8722, 8198],
 [3343, 8086, 4614, 5411, 4832],
 [6443, 5621, 5792, 8722]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8086 2639 5411 4339]
 [   0    0    0    0 8086 2639 5411 1099]
 [   0    0    0    0 8086 1844 5411 7151]
 [   0    0    0 7820 2331 8302 8722 3846]
 [   0    0    0 7820 2331 8302 8722 8198]
 [   0    0    0 3343 8086 4614 5411 4832]
 [   0    0    0    0 6443 5621 5792 8722]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 166ms/step


array([[[-3.53509560e-02, -2.74033304e-02,  9.38661024e-03,
          2.33771689e-02, -3.58989127e-02,  1.48919262e-02,
          4.47629206e-02,  2.81824730e-02,  2.78148986e-02,
          4.65614460e-02],
        [-3.53509560e-02, -2.74033304e-02,  9.38661024e-03,
          2.33771689e-02, -3.58989127e-02,  1.48919262e-02,
          4.47629206e-02,  2.81824730e-02,  2.78148986e-02,
          4.65614460e-02],
        [-3.53509560e-02, -2.74033304e-02,  9.38661024e-03,
          2.33771689e-02, -3.58989127e-02,  1.48919262e-02,
          4.47629206e-02,  2.81824730e-02,  2.78148986e-02,
          4.65614460e-02],
        [-3.53509560e-02, -2.74033304e-02,  9.38661024e-03,
          2.33771689e-02, -3.58989127e-02,  1.48919262e-02,
          4.47629206e-02,  2.81824730e-02,  2.78148986e-02,
          4.65614460e-02],
        [-1.62041187e-02,  1.43055357e-02, -3.33372951e-02,
         -4.07326706e-02, -4.08796072e-02, -3.35241109e-02,
         -1.20136030e-02, -2.66724825e-02, -3.482205

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 8086, 2639, 5411, 4339])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 106ms/step


array([[-0.03535096, -0.02740333,  0.00938661,  0.02337717, -0.03589891,
         0.01489193,  0.04476292,  0.02818247,  0.0278149 ,  0.04656145],
       [-0.03535096, -0.02740333,  0.00938661,  0.02337717, -0.03589891,
         0.01489193,  0.04476292,  0.02818247,  0.0278149 ,  0.04656145],
       [-0.03535096, -0.02740333,  0.00938661,  0.02337717, -0.03589891,
         0.01489193,  0.04476292,  0.02818247,  0.0278149 ,  0.04656145],
       [-0.03535096, -0.02740333,  0.00938661,  0.02337717, -0.03589891,
         0.01489193,  0.04476292,  0.02818247,  0.0278149 ,  0.04656145],
       [-0.01620412,  0.01430554, -0.0333373 , -0.04073267, -0.04087961,
        -0.03352411, -0.0120136 , -0.02667248, -0.03482206,  0.02554789],
       [-0.00688123,  0.01073908,  0.04773977,  0.02381689, -0.02146423,
        -0.04483841, -0.00019344, -0.0217872 ,  0.04057259,  0.0122134 ],
       [ 0.01046548, -0.02340381, -0.04116239,  0.03666308, -0.01745681,
        -0.03992549, -0.01032443,  0.02952919